CREATE TABLE DOGS (
    DOG_ID serial PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    BREED VARCHAR(200) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    OWNER_ID INT NOT NULL,
    CONSTRAINT FK_OWNER
        FOREIGN KEY(OWNER_ID)
            REFERENCES USERS(USER_ID)
);