CREATE TABLE PHOTOS (
    PHOTO_ID serial PRIMARY KEY,
    USER_ID INT NOT NULL,
    IMAGE BYTEA NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_USER
        FOREIGN KEY(USER_ID)
            REFERENCES USERS(USER_ID)
);