CREATE TABLE VET_HISTORY (
    HIST_ID serial PRIMARY KEY,
    VISIT_DATE DATE NOT NULL,
    CAUSE VARCHAR(100) NOT NULL,
    RECOMMENDATIONS TEXT NOT NULL,
    DOG_ID INT NOT NULL,
    CONSTRAINT FK_DOG
        FOREIGN KEY(DOG_ID)
            REFERENCES DOGS(DOG_ID)
);