CREATE TABLE WALKS (
    WALK_ID serial PRIMARY KEY,
    ASSIGNER_ID INT NOT NULL,
    ASSIGNEE_ID INT NOT NULL,
    DOG_ID INT NOT NULL,
    WALK_DATE TIMESTAMP NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONFIRMED BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT FK_ASSIGNER
        FOREIGN KEY(ASSIGNER_ID)
            REFERENCES USERS(USER_ID),
    CONSTRAINT FK_ASSIGNEE
        FOREIGN KEY(ASSIGNEE_ID)
            REFERENCES USERS(USER_ID),
    CONSTRAINT FK_DOG
        FOREIGN KEY(DOG_ID)
            REFERENCES DOGS(DOG_ID)
);